# config.py

# Pega aquí tu API Key real de Verificamex
ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWNkYjA4MzJlYzYyYTY1MmUxYmQwMGRmNDUzMTc1ZmU4MDUxZTg0NWNlMzI5N2ViZWRlOWE3ZmE3ZDgzYTNjNGJlODg0ZWU1ODJiMjY2OGQiLCJpYXQiOjE3NzkzMjYwNzAuMDA3OTUxLCJuYmYiOjE3NzkzMjYwNzAuMDA3OTU1LCJleHAiOjE4MTA4NjIwNjkuOTkyMjc5LCJzdWIiOiIxMTQ0NCIsInNjb3BlcyI6W119.pDX92OPQaE2HA6ul7kt7UFBvNu24eGhOvyvX1jGu07PnTRn03o93tPqRpA43AxjRW-oOjIsF278hd3OCu9iroG6PkqFiDrZLo-uIXmOeSYrJPC-xfA2MR5u_kplEr3GkGDLObFgBReymGJUexiRGzaPSoAVftOQO3FE4_P4IOOGte_NTA9boQsoUH_E44wyGAoDrz88wzrHzXZjrk2mwQbCJjZb1XMBxYS8YR-iF4oQvDc2_INU16CxlD05utzXm7s8pepzak-q7sXegCYAZxvZXjySeMh_CUnMNaN6U_1Ct6MiDdk72W59OzZII2_eVkPbq02S1ATMvCAiVFBq4xmAobmV_M3drVPMfA1YUA_EqNN2vOZS0GsuIfwO8zWvzsKj-hFyw2evHl2BfOBEp0FfkbbQtVT1wCFzZaIz5Dhav4tHjeitzxmMVBNExrJwBhfOTXMKqSQSp-4NLle_QmD0eXlK3GaxqBpKyzSr0oDRJzCstsPcPWebRivg8bdzGnSrQWNj62b29ZAiVDmOMavhx0NArUQOP-3bsMv_lGTPwwEhZnthJFXo0XUJMoEataWtrB-b2fdK4VlCSLmTZj-NkzDqlM0lvlWUrLMWWcM2KWiSNZ17MVgzg4XgHjTeopmMW2-nQK-qSzr7QyBs3j3Zj4hHdHwpiSDZuVYyWiCA"

# Pega aquí el endpoint real que te dé Verific
# API_URL = "https://api.verificamex.com/identity/v1/ine"
API_URL_INE  = "https://api.verificamex.com/identity/v1/validations/basic"

API_URL_CURP = "https://api.verificamex.com/identity/v1/scraping/renapo"

# Tiempo máximo de espera para la respuesta de la API
TIMEOUT = 120